# Generated by Django 4.1.2 on 2023-04-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison', '0008_alter_house_options_alter_meubles_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='isNegociable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meubles',
            name='isNegociable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='house',
            name='category',
            field=models.CharField(choices=[('M', 'Maison'), ('A', 'Apartement'), ('S', 'Studio'), ('C', 'Chambre')], default='maison', max_length=30),
        ),
    ]
