# Generated by Django 4.1.2 on 2023-04-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison', '0009_house_isnegociable_meubles_isnegociable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meubles',
            name='category',
            field=models.CharField(choices=[('M', 'Maison'), ('A', 'Apartement'), ('S', 'Studio'), ('C', 'Chambre')], default='maison', max_length=30),
        ),
    ]
