# Generated by Django 4.1.2 on 2023-07-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison', '0010_meubles_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meubles',
            name='category',
            field=models.CharField(choices=[('M', 'chaise'), ('A', 'Canapé'), ('S', 'lampe'), ('C', 'tabouret')], default='chaise', max_length=30),
        ),
    ]
