# Generated by Django 4.1.2 on 2023-07-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison', '0011_alter_meubles_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meubles',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
